### ISSUE TITLE
支払画面での明細表記が消えている不具合の修正

### ISSUE THREAD

**Issue by uchidaafrimedico** [afrimedico/CUORE#27]

**Comment by Uezono1** [comment]
こちらのバグ、私の確認した限り、解消しているようです。手持ちの2機種で確認しました。

アプリバージョン 7/16版
Device : Redmi 9T
OS Android 10

アプリバージョン 7/16版
Device : Huawei P20 lite
OS Android 9

**Comment by uchidaafrimedico** [comment]
以下デバイスでも問題ないこと確認しました。
アプリバージョン 7/16版
Device : Huawei T17.0LTE2G/16G/DL09C
OS Android 6
