### ISSUE TITLE
英語<- -> スワヒリ語の切り替えができない

### ISSUE THREAD

**Issue by Michisome** [afrimedico/CUORE#36]
Uchida 
システム言語を英語にしてもスワヒリ表記が入ります。
![image (1)](https://user-images.githubusercontent.com/61012718/125800679-6a3db514-c923-4add-b167-42d33e52dedb.png)
![image (2)](https://user-images.githubusercontent.com/61012718/125800700-5785799d-c059-43d4-b272-c6b4bae80c38.png)

**Comment by Michisome** [comment]
OSの言語が英語でない場合、全てスワヒリ語に切り替えをするようにしていますが、どのように修正をすればよいでしょうか？

Uchida
@longnh 失礼しました。でしたら問題ありません。<(_ _)>

longnh 
@yosuke hirano @Uchida
最新版の APKファイルを送らせていただきます。ご確認をお願いします。
宜しくお願いします。

**Comment by Michisome** [comment]
afrimedico 
@longnh スワヒリ表記は直ったようです

**Comment by Michisome** [comment]
そめ
私のスマホでテストすると言語設定を変更しても常に英語で表示されます。
操作など誤りがあれば教えてください。
 Device  SH-M08 
 OS       Android 10

第1言語　　　　CUOREの表記
スワヒリ語　→　英語
英語（U.S.） →　英語
日本語　　　→　英語
![2_R](https://user-images.githubusercontent.com/61012718/125935835-1c6029c4-bb70-497b-90c5-b4cdc0c22d45.jpg)
![3_R](https://user-images.githubusercontent.com/61012718/125935837-5136b72c-6b59-4eb7-857c-3250d16074f9.jpg)
![8_R](https://user-images.githubusercontent.com/61012718/125935823-5f63c116-8fa9-4273-b449-6e4a6c2e70cb.jpg)
![9_R](https://user-images.githubusercontent.com/61012718/125935830-00078a1c-5e4c-4fbb-9253-84aac170f528.jpg)
![10_R](https://user-images.githubusercontent.com/61012718/125935831-d090bf81-2092-4cf5-a3f8-b3b00c150071.jpg)
![12_R](https://user-images.githubusercontent.com/61012718/125935833-27070a28-a974-47fa-bcba-e58ae12d4972.jpg)

**Comment by uchidaafrimedico** [comment]
7/15APKで以下の状態。

1.OS言語＝英語のとき、英語表記（OK）
2.OS言語＝スワヒリのとき、英語表記（NG）

2の現象が起きているデバイスは、

デバイス1：
Device SH-M08
OS Android 10

デバイス2：
Zenfone Live L1 
Android 8.0.0

の2台で確認しています。

**Comment by Michisome** [comment]
longnh 
1.OS言語＝英語のとき、英語表記（OK）
2.OS言語＝スワヒリのとき、英語表記（NG）
@afrimedico
アプリを完全に閉じてから再度アプリを立ち上げてみていただけますでしょうか？

**Comment by huulong131** [comment]
再度修正させて頂きましたので、後ほどAPKをお送らせて頂きます。

**Comment by Michisome** [comment]
Uchida
言語設定をスワヒリ語にし、アプリを完全に閉じてから再度アプリ立ち上げましたが、英語表記でした。スワヒリ語でもタンザニア、ケニア、ウガンダ、コンゴの4種類があったので、念のため全部で上記作業を繰り返しましたが結果は変わりませんでした。
アプリのアンインストール、再インストールもして試してみましたが、やはりNGでした。

そめ補足
こちらの結果は以下の端末です。
Zenfone Live L1
Android 8.0.0

**Comment by Michisome** [comment]
アプリを完全に閉じてからアプリを立ち上げましたが結果は変わらないです。
第1言語　　　　CUOREの表記
スワヒリ語　→　英語
英語（U.S.） →　英語
日本語　　　→　英語

使用アプリ　0715版
スマホ：SH-M08、OS Android 10

なおアプリを完全に閉じるというのは以下の操作のことを指します。
1.リセントキーからアプリのプロセス一覧を出す
2.上にスワイプする。
１
![1_R](https://user-images.githubusercontent.com/61012718/125934220-41c4df61-460b-4941-b35d-f21849545257.jpg)

２
![2_R](https://user-images.githubusercontent.com/61012718/125934223-4a1c6b28-7d29-411d-b712-529cea8a353c.jpg)

**Comment by huulong131** [comment]
この後お送りするAPKで再度ご確認下さい。

**Comment by Michisome** [comment]
解消していました。
第1言語 　　　　 CUOREの表記
 スワヒリ語　→　スワヒリ語
 英語（U.S.） →　英語
 日本語            →　スワヒリ語
アプリバージョン：7/16版
Device SH-M08
OS Android 10

**Comment by uchidaafrimedico** [comment]
デバイス2：
Zenfone Live L1
Android 8.0.0

でも問題無いことを確認しました。
