### ISSUE TITLE
NW接続に問題ない状態でも送信がエラーになる

### ISSUE THREAD

**Issue by Michisome** [afrimedico/CUORE#37]
電話回線はOFF（機内モード）にしWiFi接続だけの状態で送信できません。

@longnh 電話回線ONで再度送信しましたが、同じ現象です。

**Comment by huulong131** [comment]
WiFi接続では、問題なく送信できました。
電話回線ONの場合ですが、こちらで不具合を確認できませんでした。回線の通信には問題がないか？ご確認いただけますでしょうか？

**Comment by Michisome** [comment]
Azureに通信が到達していることを確認しました。＝送信できている。
【実施環境】
Wifiのみ:ok
Mobileのみ:ok
実施スマホ
アプリバージョン：7/16版
Device SH-M08
OS Android 10
