### ISSUE TITLE
Ring upのポップアップ画面でCancelをタップすると、画面が黒くなる

### ISSUE THREAD

**Issue by Michisome** [afrimedico/CUORE#39]
上薗秀正  00:46
Ring upのポップアップ画面でCancelをタップすると、画面が黒くなります

**Comment by huulong131** [comment]
確認しましたが、再現できません。

**Comment by Michisome** [comment]
再現しませんでした。
アプリバージョン：7/16版
Device SH-M08
OS Android 10

**Comment by Uezono1** [comment]
7/13リリースバージョンでは発生していましたが、7/16バージョンでは改善していることを確認しました

アプリバージョン：7/16版
Device : Redmi 9T
OS Android 10
