### ISSUE TITLE
AddとCount画面が空白

### ISSUE THREAD

**Issue by Michisome** [afrimedico/CUORE#40]
Uchida

![2021-07-12 21 24 23](https://user-images.githubusercontent.com/61012718/125804574-86ca282f-3825-4406-9e87-72f4623ea864.png)
![2021-07-12 21 24 28](https://user-images.githubusercontent.com/61012718/125804584-140a2ad1-c880-4981-b173-a906415691e6.png)

**Comment by huulong131** [comment]
@uchidaafrimedico 
こちらの件、対応させて頂きました。

**Comment by Michisome** [comment]
解消していることを確認しました。
アプリバージョン：7/16版
Device SH-M08
OS Android 10 

![2_R_R](https://user-images.githubusercontent.com/61012718/126039797-98802efe-bd46-4db2-acfc-ad32f2432ce4.jpg)
![３_R](https://user-images.githubusercontent.com/61012718/126039798-01dd48ef-f424-4938-9db2-9b5db90fa28b.jpg)
